### ISSUE TITLE
Usage of console.log in lib.js

### ISSUE THREAD

**Issue by drdrwhite** [yjs/y-prosemirror#100]
* [ arguably ] Are you reporting a bug? 
* [ X ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
The main branch includes a console.log invocation in src/lib.js line 29

**To Reproduce**
1. Go to a website using y-prosemirror
2. Open console
3. See "testing what I wanted to test. lol Object"

**Expected behavior**
Not sure if this is a bug, but seems unusual to ship console logs. Raising this for discussion.

**Screenshots**

**Environment Information**
 - Browser / Node.js [e.g. Chrome, Firefox, Node.js]
 - Yjs version and the versions of the y-* modules you are using [e.g. yjs v13.0.1, y-webrtc v1.2.1]. Use `npm ls yjs` to find out the exact version you are using.

Chrome
HEAD @ 7b7ea52
y-prosemirror@1.0.16 

**Additional context**
N/A

**Comment by dmonad** [comment]
Oh no.. thank you for reporting! Fixed and published.
