### ISSUE TITLE
Prosemirror document doesn't get populated with Yjs doc content (sync plugin)

### ISSUE THREAD

**Issue by ronnyroeller** [yjs/y-prosemirror#106]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
I initialize a Yjs document with updates from the database, and then create a Prosemirror editor linked to this Yjs document (sync plugin). Doing so, the Prosemirror editor isn't populated with the content from the Yjs document.

Note: I'm running the code on the server-side (NodeJS) - not in a browser!

_This issue was initially discussed in the [Yjs Community forum](https://discuss.yjs.dev/t/create-yjs-prosemirror-updates-programmatically/1111)._

**To Reproduce**
Minimal reproduction case: https://github.com/ronnyroeller/y-prosemirror-update (see README for execution instructions) 

It shows that the Prosemirror doc doesn't contain the content from the Yjs doc:
![image](https://user-images.githubusercontent.com/9339055/167248104-ee7f0b29-5b40-451e-ac9f-a803cb4fcfac.png)

**Expected behavior**
Prosemirror editor contains content from the Yjs document.

**Environment Information**
 - Node.js: v17.8.0
 - yjs@13.5.35
 - y-prosemirror@1.0.19

**Comment by dmonad** [comment]
Looking through this again, it makes sense. y-prosemirror plugins operate on the view. So it's natural that it doesn't work if you don't have a view.

**Comment by ronnyroeller** [comment]
Thanks for the explanation, @dmonad 
Closing this ticket as it's expected behavior.
