### ISSUE TITLE
On long docs the editor can scroll for other collab users

### ISSUE THREAD

**Issue by vwall** [yjs/y-prosemirror#14]
We ran into a problem in a long doc and a user outside of the view port.  The user will get scrolled when someone starts typing.  Just checked the demo site https://yjs.dev/ and it also has this issue.

**Comment by vwall** [comment]
@dmonad  I was able to remove this issue by deleting this line.  Does this seem like a reasonable fix?

https://github.com/yjs/y-prosemirror/blob/master/src/plugins/sync-plugin.js#L320

**Comment by dmonad** [comment]
@vwall Yes, this fix makes more sense than the current solution. The idea was that the editor content automatically adapts the window location when another user changes content. Unfortunately, this is not yet fully worked out.

**Comment by vwall** [comment]
Would you accept a pull-request that maybe just comments that part out for now?  We had to recreate the sync-plugin to avoid this issue.

**Comment by dmonad** [comment]
Sure

**Comment by dmonad** [comment]
@boschDev is currently working on this #18

**Comment by dmonad** [comment]
Fixed in 0.3.7
