### ISSUE TITLE
Cannot read properties of undefined (reading 'nodeSize')

### ISSUE THREAD

**Issue by mendesanna** [yjs/y-prosemirror#162]
Hello
I'm still having this exact issue(https://github.com/yjs/y-prosemirror/issues/156) even though I have this latest version:
```
TypeError: Cannot read properties of undefined (reading 'nodeSize')
    at relativePositionToAbsolutePosition (chunk-4AVB3MJ2.js?v=3879bf73:263:37)
    at chunk-4AVB3MJ2.js?v=3879bf73:1171:20
    at Map.forEach (<anonymous>)
    at createDecorations (chunk-4AVB3MJ2.js?v=3879bf73:1157:25)
    at Plugin.init (chunk-4AVB3MJ2.js?v=3879bf73:1215:14)
    at _EditorState.reconfigure (chunk-LUJVU6BP.js?v=3879bf73:2580:75)
    at Editor2.createView (chunk-XN66PWTN.js?v=3879bf73:9440:33)
    at new Editor (chunk-XN66PWTN.js?v=3879bf73:9261:10)
    at new Editor2 (@tiptap_react.js?v=411d6cd6:3312:5)
    at @tiptap_react.js?v=411d6cd6:3620:14
```
I'm using y-prosemirror through Tiptap and I've checked they are using the latest version 1.2.9.
Is there something else missing here? Can anyone help me?

_Originally posted by @mendesanna in https://github.com/yjs/y-prosemirror/issues/156#issuecomment-2245332566_

**Comment by nyacg** [comment]
We're also experiencing this

**Comment by dmonad** [comment]
I really thought a lot about the bug report template. I usually don't even look at comments that post only error messages without steps for reproduction. I mention that specifically in the template:

> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

You are receiving free software and free help. I don't think I'm asking for too much.

It is working for the original ticket author. So what are you doing differently? Please open a new ticket. Fill out the bug report and show me how to reproduce the issue.
