### ISSUE TITLE
Editing blocked because of cursor position error

### ISSUE THREAD

**Issue by AntoLC** [yjs/y-prosemirror#173]
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

When we are multiples users editing in the same time, a cursor error appears sometimes (hard to reproduce).
When the error appear it becomes impossible for everybody to edit.

**Errors log**

```
Unhandled Runtime Error

TypeError: Range.setStart: Argument 1 is not an object.
Call Stack
_isDomSelectionInView
javascript\node_modules\y-prosemirror\src\plugins\sync-plugin.js (334:1)
_isLocalCursorInView
javascript\node_modules\y-prosemirror\src\plugins\sync-plugin.js (325:1)
_typeChanged/<
javascript\node_modules\y-prosemirror\src\plugins\sync-plugin.js (560:1)
createMutex/<
javascript\node_modules\lib0\mutex.js (35:1)
_typeChanged
javascript\node_modules\y-prosemirror\src\plugins\sync-plugin.js (526:1)
callAll
javascript\node_modules\lib0\function.js (19:1)
callEventHandlerListeners
javascript\node_modules\yjs\dist\yjs.mjs (1984:3)
cleanupTransactions/</<
javascript\node_modules\yjs\dist\yjs.mjs (3278:1)
cleanupTransactions/<
javascript\node_modules\yjs\dist\yjs.mjs (3259:1)
callAll
javascript\node_modules\lib0\function.js (19:1)
cleanupTransactions
javascript\node_modules\yjs\dist\yjs.mjs (3283:14)
transact
javascript\node_modules\yjs\dist\yjs.mjs (3409:1)
readUpdateV2
javascript\node_modules\yjs\dist\yjs.mjs (1649:1)
applyUpdateV2
javascript\node_modules\yjs\dist\yjs.mjs (1744:1)
applyUpdate
javascript\node_modules\yjs\dist\yjs.mjs (1758:1)
```

**Potential solution**
Here:
https://github.com/yjs/y-prosemirror/blob/df4257b499bf25b2b8e69d56cc2d8bb790f8e7ba/src/plugins/sync-plugin.js#L325
```diff
+      try {
+          this._domSelectionInView = this._isDomSelectionInView()
+      }
+      catch (e) {
+         this._domSelectionInView = false
+      }

-      this._domSelectionInView = this._isDomSelectionInView() 

... 
```
It will not solve the bug but it will not block the editing anymore.

--- 

Thank you !

**Comment by YousefED** [comment]
Nice find! Instead of a try / catch we probably want to handle the case a bit more cleanly (for example, handling "None" selection?). I hope @dmonad can weigh in, see https://github.com/numerique-gouv/impress/issues/440 for more details

**Comment by dmonad** [comment]
Thanks for the stack trace!

I don't like catching errors that I didn't expect. So I tried fixing the underlying cause. I could imagine that if there is no dom selection, there would be an exception because `selection.anchorNode` is null in `sync-plugin.js#334`. Now the code guards against this behavior.

I just published a new release that, hopefully, fixes this issue. Please reopen this ticket if you can produce a new stack trace.
