### ISSUE TITLE
Repo has implicit dependencies on lib0/y-protocols

### ISSUE THREAD

**Issue by tommoor** [yjs/y-prosemirror#25]
**Describe the bug**
Repo has implicit dependencies on lib0/y-protocols, it's not clear exactly what the requirements are to work on the repo independently.

**To Reproduce**
1. clone repo
2. run `npm install`
3. run `npm run dist` or `npm run debug`
4. Fails with error

```
[!] Error: Could not load /Users/tom/projects/y-prosemirror/../lib0/testing.js (imported by test/index.js): ENOENT: no such file or directory, open '/Users/tom/projects/y-prosemirror/../lib0/testing.js'
```

**Expected behavior**

The repo should be useable and allow for development without additional repos implicitly required. Or, the development instructions should make it clear what the setup should be to allow for local development.

**Screenshots**

![image](https://user-images.githubusercontent.com/380914/95801400-166d3d00-0caf-11eb-82f5-4abd8aaab329.png)

**Additional context**

Working on a fork to add additional functionality

**Comment by dmonad** [comment]
Hey @tommoor , I double checked, and I don't think that lib0 is imported using a relative path (anymore?).

I certainly do something like that from time to time when I develop new features, and I might have accidentally committed that change. But the current `master` branch does not use relative paths to lib0: https://github.com/yjs/y-prosemirror/blob/master/test/index.js

Maybe you are on an old branch?

**Comment by tommoor** [comment]
![image](https://user-images.githubusercontent.com/380914/95889415-38aa9d80-0d37-11eb-96ac-20dc598d0dd2.png)

Branch is uptodate, I cloned yesterday. I'd recommend you give it a quick try in a fresh clone location

**Comment by dmonad** [comment]
So sorry about that -.- 

So I wrote this bundler plugin that imports from relative positions. I haven't used it in a while, but it should only work when a environment flag is set.  Seems I hastily ported the plugin and forgot to set the environment variable. 

It is fixed now!
