### ISSUE TITLE
Can't run in node

### ISSUE THREAD

**Issue by estebanprimost** [yjs/y-prosemirror#7]
Hi @dmonad. We are trying to use your this binding from node ([this function particularly](https://github.com/yjs/y-prosemirror/blob/046d0e48cabe482f002f480a7f34a5573c17f1b0/src/plugins/sync-plugin.js#L361)), but found some problems on require:

```
> const yProsemirror = require('y-prosemirror')
Thrown:
/home/ejp4/dev/testing-y-prosemirror/node_modules/y-protocols/awareness.js:5
import * as encoding from 'lib0/encoding.js'
       ^

SyntaxError: Unexpected token *
```

I think [this PR](https://github.com/yjs/y-prosemirror/pull/6) should solve it.

Thanks.

**Comment by dmonad** [comment]
Hi @estebanprimost , thanks for bringing this up and providing a fix for it. I forgot to overwrite the imports for the distribution build. I fixed this in a separate PR.
