### ISSUE TITLE
ESM issue: ./dist/y-prosemirror.mjs doesn't exist

### ISSUE THREAD

**Issue by ohardy** [yjs/y-prosemirror#79]
**Describe the bug**
In package.json:

```json
"exports": {
    ".": {
      "import": "./dist/y-prosemirror.mjs",
      "require": "./dist/y-prosemirror.cjs"
    }
  },
```

but the file dist/y-prosemirror.mjs doesn't exist in the package.

**To Reproduce**
Use y-prosemirror with webpack, it will fail with: Module not found: Error: Can't resolve 'y-prosemirror'

**Expected behavior**
./dist/y-prosemirror.mjs file should exist or be replaced with ./dist/y-prosemirror.cjs

The issue appear only with the last version. Installing version 1.0.9 fix the bug because no "exports" in package.json

**Comment by dmonad** [comment]
Whoops, sorry for that. I fixed it in v.1.0.10.
